#Application Name
spring:
  application:
    name: zuul-server     #nombre del archivo remoto
  cloud:
    config:
      uri: http://localhost:8888  #donde spring cloud config esta ejecutantonse
      fail-fast: true             #si no encuentra el servicio